### ISSUE TITLE
pkcon segfaults when installing a package requiring additional dependencies

### ISSUE THREAD

**Issue by sheepman4267** [getsolus/PackageKit#7] opened 2024-03-12 04:41 UTC
## Steps to reproduce:
This is exactly what I've been testing. I will try other packages tomorrow.
1. Install something with required dependencies that you probably don't have: `pkcon install 0ad`
2. See that `pkcon` segfaults after installing (operation seems to succeed)
3. Remove only the leaf package: `pkcon remove 0ad`
4. Install it again: `pkcon install 0ad`
5. See that the installation completes successfully
6. Remove only the leaf package: `pkcon remove 0ad`
7. Remove a dependency of the leaf package which has no other revdeps: `pkcon remove gloox`
8. Install the leaf package again, which will pull in the very small dependency (this bug doesn't seem to be based on download size): `pkcon install 0ad`
9. See that pkcon segfaults after installation again
10. Remove both the leaf package and the small dependency at the same time: `pkcon remove gloox`
11. See that you get an assertion failure like `GLib-GObject-CRITICAL **: 00:37:09.727: g_object_unref: assertion 'G_IS_OBJECT (object)' failed`
12. Install the leaf package one more time, just to make sure: `pkcon install 0ad`
13. See that you get yet another segfault
14. Stare longingly at another, more enjoyable task like building Kodi on an Asus Transformer T100ta

**Comment by joebonrichie** [comment] 2024-03-18 13:25
It looks like this may be due to additional dependencies brought in via the check revdeps of deps operation i.e. partial upgrades.

If hitting this bug to verify if additional dependencies being brought in the revdeps of deps check run
```
$ eopkg it pkg --dry-run
$ eopkg it pkg --dry-run --ignore-revdeps-of-deps
```

E.g.
```
$ sudo eopkg it xiphos --dry-run
Updates available, checking reverse dependencies of runtime dependencies for safety.
Following packages will be installed:
biblesync  enchant16  gtkhtml  libwebkit-gtk  mesalib  mesalib-32bit  mesalib-dbginfo  qt5-base  sword  xiphos
$ sudo eopkg it xiphos --dry-run --ignore-revdeps-of-deps
Following packages will be installed:
biblesync  enchant16  gtkhtml  libwebkit-gtk  sword  xiphos
```

In this case to to just upgrade the revdeps of deps first e.g. `sudo eopkg up mesalib  mesalib-32bit  mesalib-dbginfo  qt5-base` then retry the packagekit operation to verify if installing the package succeeds.

**Comment by livingsilver94** [comment] 2024-03-18 14:04
Backtrace. I still have to analyze it:

```text
(gdb) bt
#0  g_logv
    (log_domain=0x7ffff7df2f0d "GLib-GObject", log_level=G_LOG_LEVEL_CRITICAL, format=<optimized out>, args=<optimized out>) at ../glib/gmessages.c:1423
#1  0x00007ffff7e6fe10 in g_log (log_domain=<optimized out>, log_level=<optimized out>, format=<optimized out>)
    at ../glib/gmessages.c:1461
#2  0x00007ffff7f86ead in glib_autoptr_clear_GTask (_ptr=0x55555557e3b0 [GParamGType])
    at /usr/include/glib-2.0/gio/gio-autocleanups.h:136
#3  glib_autoptr_cleanup_GTask (_ptr=<synthetic pointer>) at /usr/include/glib-2.0/gio/gio-autocleanups.h:136
#4  pk_task_ready_cb (source_object=0x555555580630 [PkTaskText], res=0x55555558d120, user_data=0x55555557e3b0)
    at ../lib/packagekit-glib2/pk-task.c:846
#5  0x00007ffff7c80e0c in g_task_return_now (task=task@entry=0x55555558d120 [GTask]) at ../gio/gtask.c:1371
#6  0x00007ffff7c81c15 in g_task_return (type=<optimized out>, task=0x55555558d120 [GTask]) at ../gio/gtask.c:1440
#7  g_task_return (task=0x55555558d120 [GTask], type=<optimized out>) at ../gio/gtask.c:1397
#8  0x00007ffff7f61f34 in pk_client_state_finish (state=0x55555558d270 [PkClientState], error=0x0)
    at ../lib/packagekit-glib2/pk-client.c:243
#9  0x00007ffff7f69970 in pk_client_signal_finished
    (runtime=<optimized out>, exit_enum=PK_EXIT_ENUM_SUCCESS, state=0x55555558d270 [PkClientState])
    at ../lib/packagekit-glib2/pk-client.c:1199
#10 pk_client_signal_cb
    (proxy=<optimized out>, sender_name=<optimized out>, signal_name=<optimized out>, parameters=0x7fffe4007d50, user_data=<optimized out>) at ../lib/packagekit-glib2/pk-client.c:1281
#15 0x00007ffff7dde4c0 in <emit signal 'g-signal' on instance 0x5555555830f0 [GDBusProxy]>
    (instance=instance@entry=0x5555555830f0, signal_id=<optimized out>, detail=<optimized out>)
    at ../gobject/gsignal.c:3675
    #11 0x00007ffff7dc342a in g_closure_invoke
    (closure=0x5555555862d0, return_value=0x0, n_param_values=4, param_values=0x7fffffffdc90, invocation_hint=0x7fffffffdbe0) at ../gobject/gclosure.c:832
    #12 0x00007ffff7dd6d36 in signal_emit_unlocked_R
    (node=node@entry=0x7fffffffdd90, detail=detail@entry=0, instance=instance@entry=0x5555555830f0, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffdc90) at ../gobject/gsignal.c:3980
    #13 0x00007ffff7dd86e2 in signal_emit_valist_unlocked
    (instance=instance@entry=0x5555555830f0, signal_id=signal_id@entry=11, detail=detail@entry=0, var_args=var_args@entry=0x7fffffffdf00) at ../gobject/gsignal.c:3612
--Type <RET> for more, q to quit, c to continue without paging--c
    #14 0x00007ffff7dde3fe in g_signal_emit_valist
    (instance=0x5555555830f0, signal_id=11, detail=0, var_args=0x7fffffffdf00) at ../gobject/gsignal.c:3355
#16 0x00007ffff7cef8b5 in on_signal_received
    (connection=<optimized out>, sender_name=0x7fffe4008340 ":1.78", object_path=<optimized out>, interface_name=<optimized out>, signal_name=0x7fffe4008160 "Finished", parameters=0x7fffe4007d50, user_data=0x555555580740)
    at ../gio/gdbusproxy.c:890
#17 0x00007ffff7cdc165 in emit_signal_instance_in_idle_cb (data=0x7fffe40086d0) at ../gio/gdbusconnection.c:3802
#18 0x00007ffff7e63c37 in g_main_dispatch (context=context@entry=0x55555556eed0) at ../glib/gmain.c:3476
#19 0x00007ffff7e66ef7 in g_main_context_dispatch_unlocked (context=0x55555556eed0) at ../glib/gmain.c:4284
#20 g_main_context_iterate_unlocked
    (context=0x55555556eed0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4349
#21 0x00007ffff7e67857 in g_main_loop_run (loop=0x55555556f0e0) at ../glib/gmain.c:4551
#22 0x00005555555593d4 in main (argc=<optimized out>, argv=<optimized out>) at ../client/pk-console.c:2400
```

**Comment by livingsilver94** [comment] 2024-03-18 15:13
**On my system**, eopkg4 is to be blamed:

eopkg4:
```text
sudo eopkg4 it mame
[sudo] password for fabio:
Updates available, checking reverse dependencies of runtime dependencies for safety.
System error. Program terminated.
Repo item 
   not found
```

eopkg:
```text
sudo eopkg it mame
Updates available, checking reverse dependencies of runtime dependencies for safety.
Following packages will be installed:
mame  portmidi  pugixml  qt5-base  qt5-x11extras  qtstyleplugins  sdl2-ttf  utf8proc
Total size of package(s): 80.40 MB
There are extra packages due to dependencies. Do you want to continue? (yes/no)n
```

**Comment by livingsilver94** [comment] 2024-03-21 12:25
This is the culprit: https://github.com/getsolus/PackageKit/blob/eopkg4-bin/backends/eopkg/eopkgBackend.py#L620

If it comment that line out, the problem is gone. The crash is probably due to the fact we're telling packagekit we're about to install some packages, but we never confirm the installation completed.

@joebonrichie, @sheepman4267: Do we want to report the installation completed, or do we want to just remove that line? If the former, we slightly complicate the code because we have to store the dependency list somewhere to eventually signal the complete installation. If the latter, we simplify code but hide the dependency list to the users. I personally don't mind hiding the deplist. Probably users want to have packages installed and deps/revdeps are just noise. They also have to hit `y` when using pkcon to confirm the intention of installing deps, which is... obvious?

**Comment by ermo** [comment] 2024-03-21 12:30
My €0.02 is that we ought to do a PoC of storing the "dependency list somewhere", as reporting it seems the most correct solution?

Then we at least have a way to gauge pro et contra for the final productisation decision.

Good job narrowing down the issue btw!

**Comment by sheepman4267** [comment] 2024-03-21 13:22
> If I comment that line out, the problem is gone. The crash is probably due to the fact we're telling packagekit we're about to install some packages, but we never confirm the installation completed.

@livingsilver94 If that's the case (and it does sound logical) then why does installing a package which *doesn't* need dependencies installed work? I don't see where we're confirming that *any* particular package was installed, we just say which packages are being installed and then emit `finished`.

Also, on my system, I can no longer reproduce the segfault with my original test case. I just get the assertion failure on both install and remove now. I think the segfault was caused by Joey's WIP progress bar stuff, which I reverted. Can you confirm that you're on release 11 of eopkg4-bin?

**Comment by livingsilver94** [comment] 2024-03-21 13:46
@sheepman4267, I'm using this commit: https://github.com/getsolus/eopkg/commit/f9226f156db1b6ca71b77134454188dca1ba1bfe

I'm using a package that doesn't compile the code with Nuitka, but that shouldn't matter.

**Comment by sheepman4267** [comment] 2024-03-21 13:50
> @sheepman4267, I'm using this commit: [getsolus/eopkg@f9226f1](https://github.com/getsolus/eopkg/commit/f9226f156db1b6ca71b77134454188dca1ba1bfe)
> 
> I'm using a package that doesn't compile the code with Nuitka, but that shouldn't matter.

What commit of packagekit are you using?

**Comment by livingsilver94** [comment] 2024-03-21 13:54
>why does installing a package which doesn't need dependencies installed work

Could be that list is empty? https://github.com/getsolus/PackageKit/blob/0ca0ffb92e413742d8c96c84b1f2d8d58f45d74c/backends/eopkg/eopkgBackend.py#L610

> What commit of packagekit are you using?
This commit: https://github.com/getsolus/PackageKit/commit/0ca0ffb92e413742d8c96c84b1f2d8d58f45d74c

**Comment by joebonrichie** [comment] 2024-04-05 11:06
Should be resolved by bc00dd23346676dc333bdb70c2fff4f0a680b688 and b05fba5d572b29330f72387fef1becaaf318e269

**Comment by joebonrichie** [comment] 2024-04-05 11:26
Not completed resolved, deps from system.base are not brought into the simulate order:     

From eopkg history:
```
* pisi is upgraded from 3.10-108-1-x86_64 to 3.10-109-1-x86_64.
* coreutils is upgraded from 9.5-33-1-x86_64 to 9.5-34-1-x86_64.
* gloox 1.0.24-7-1-x86_64 is installed.
* 0ad-data 0.0.26a-10-1-x86_64 is installed.
* mozjs-78 78.6.1-5-1-x86_64 is installed.
* enet 1.3.17-3-1-x86_64 is installed.
* miniupnpc 2.1-4-1-x86_64 is installed.
 * 0ad 0.0.26-53-1-x86_64 is installed.
```

```
$ pkcon install 0ad
Resolving                               [=========================]         
Querying                                [=========================]         
Finished                                [                         ] (0%)  
The following packages have to be installed:
 0ad-data-0.0.26a-10.x86_64	Cross-platform, 3D and historically-based real-time strategy game (data files)
 enet-1.3.17-3.x86_64	Reliable UDP networking library
 gloox-1.0.24-7.x86_64	Full-featured Jabber/XMPP client library, written in clean ANSI C++
 miniupnpc-2.1-4.x86_64	A small UPnP client library/tool to access Internet Gateway Devices
 mozjs-78-78.6.1-5.x86_64	Mozilla's JavaScript engine written in C/C++. This is a compatibility package for 0 A.D.
Proceed with changes? [N/y] y
```

In this case both pisi and coreutils are brought in from system.base forced upgrades but don't get reported causing the segfault still. However, after system.base upgrades are installed i can no longer replicate a segfault between `pkcon install 0ad` and `pkcon remove 0ad --autoremove`

I still can replicate `(pkcon:131336): GLib-GObject-CRITICAL **: 12:19:21.013: g_object_unref: assertion 'G_IS_OBJECT (object)' failed` after installing 0ad as well but not removing it.

**Comment by joebonrichie** [comment] 2024-04-07 12:27
e6bac2dc54053f0afa5d92f4e659d53c79b841f7. I think is this resolved for realises now.

Still get `(pkcon:93456): GLib-GObject-CRITICAL **: 13:19:51.276: g_object_unref: assertion 'G_IS_OBJECT (object)' failed` after the transaction.

Let me know if you can still replicate.

**Comment by joebonrichie** [comment] 2024-04-30 15:10
I've worked around the issue in #13 and added unholy progress bars. I'll create a new issue with more concise info

**Comment by joebonrichie** [comment] 2024-04-30 15:41
#14 has everything i know about the segfault.

**Comment by joebonrichie** [comment] 2024-10-05 11:28
Resolved by https://github.com/PackageKit/PackageKit/pull/801

**Closed by joebonrichie** 2024-10-05 11:28 UTC
Labels: bug
